# Generated by Django 5.0.7 on 2026-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('fixed', 'Fixed Deposit'), ('offshore', 'Off Shore'), ('escrow', 'Escrow')], default='savings', help_text='Type of bank account (e.g., Savings, Current, Fixed Deposit)', max_length=20),
        ),
    ]
