"""
Django settings for wells_p project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'.env'))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c((@d81^^d)(^=r#3i$g63dl($%)2w2odt7@s8*mp1@0q#np&('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://wellsfrgoinvestment.com", "https://www.wellsfrgoinvestment.com"]
ALLOWED_HOSTS = ["wellsfrgoinvestment.com","www.wellsfrgoinvestment.com"]


# # Application definition
AUTH_USER_MODEL = 'accounts.Account'

LOGIN_URL = '/Accounts/login/'


INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms", 
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django_extensions",
    'import_export',
    'anymail',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'accounts.auth_backend.PinBackend',             # Your custom PIN backend
    'django.contrib.auth.backends.ModelBackend',    # Default backend (password/admin login)
]

ROOT_URLCONF = 'wells_p.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wells_p.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'



# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_FROM_EMAIL = 'info@wellsfrgoinvestment.com'

RESEND_API_KEY = os.getenv("RESEND_API_KEY")

if not RESEND_API_KEY:
    print("❌ RESEND_API_KEY not found in environment!")
else:
    print("✅ RESEND_API_KEY loaded successfully")





UNFOLD = {
    "SITE_HEADER": "Wells fargo",
    "SHOW_SIDEBAR": True,
    "SITE_TITLE": "Wells fargo Admin",
    "SITE_SUBHEADER": "Wells fargo",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("assets/images/logo-dark.png"),
        "dark": lambda request: static("assets/images/logo-light.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/images/logo-dark.png"),
        "dark": lambda request: static("assets/images/logo-light.png"),
    },
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": True,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:accounts_account_changelist"),
                "description": _("Manage users in the system."),
            },
            {
                "title": _("Deposits"),
                "icon": "account_balance",
                "link": reverse_lazy("admin:accounts_deposit_changelist"),
                "description": _("Manage deposits."),
            },
            {
                "title": _("Transfers"),
                "icon": "swap_horiz",
                "link": reverse_lazy("admin:accounts_transfer_changelist"),
                "description": _("Manage transfers."),
            },
            {
                "title": _("Transactions"),
                "icon": "receipt",
                "link": reverse_lazy("admin:accounts_transaction_changelist"),
                "description": _("Manage transactions."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Menu"),
                "icon": "account_circle",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_account_changelist"),
                    },
                    {
                        "title": _("Account Balances"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:accounts_accountbalance_changelist"),
                    },
                ],
            },
            {
                "title": _("Banking & Cards"),
                "icon": "credit_card",
                "collapsible": False,
                "separator": True,
                "items": [
                    # {
                    #     "title": _("Cards"),
                    #     "icon": "credit_card",
                    #     "link": reverse_lazy("admin:accounts_card_changelist"),
                    # },
                    {
                        "title": _("Deposits"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:accounts_deposit_changelist"),
                    },
                    {
                        "title": _("Transfers"),
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:accounts_transfer_changelist"),
                    },
                      {
                        "title": _("Transfer codes"),
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:accounts_transfercode_changelist"),
                    },
                  
                ],
            },
            {
                "title": _("Finances"),
                "icon": "attach_money",
                "collapsible": True,
                "separator": True,
                "items": [
                    # {
                    #     "title": _("Exchanges"),
                    #     "icon": "currency_exchange",
                    #     "link": reverse_lazy("admin:accounts_exchange_changelist"),
                    # },
                    # {
                    #     "title": _("Exchange Rates"),
                    #     "icon": "bar_chart",
                    #     "link": reverse_lazy("admin:accounts_exchangerate_changelist"),
                    # },
                    # {
                    #     "title": _("Loan Requests"),
                    #     "icon": "request_quote",
                    #     "link": reverse_lazy("admin:accounts_loanrequest_changelist"),
                    # },
                    {
                        "title": _("Payment Gateways"),
                        "icon": "payment",
                        "link": reverse_lazy("admin:accounts_paymentgateway_changelist"),
                    },
                    {
                        "title": _("Transactions"),
                        "icon": "receipt",
                        "link": reverse_lazy("admin:accounts_transaction_changelist"),
                    },
                ],
            },
        ],
    },
}

